# coding: utf-8

"""
    AWS Docs API

    API for AWS Docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from aws_api_python_runtime.paths.tags.post import CreateFormReviewWorkflowTag
from aws_api_python_runtime.paths.schemas.post import CreateFormSchema
from aws_api_python_runtime.paths.schemas_schema_id.delete import DeleteFormSchema
from aws_api_python_runtime.paths.documents_document_id.get import GetDocument
from aws_api_python_runtime.paths.documents_document_id_forms_form_id.get import GetDocumentForm
from aws_api_python_runtime.paths.documents_upload_url.get import GetDocumentUploadUrl
from aws_api_python_runtime.paths.schemas_schema_id.get import GetFormSchema
from aws_api_python_runtime.paths.metrics.get import GetMetrics
from aws_api_python_runtime.paths.documents_document_id_forms.get import ListDocumentForms
from aws_api_python_runtime.paths.documents.get import ListDocuments
from aws_api_python_runtime.paths.tags.get import ListFormReviewWorkflowTags
from aws_api_python_runtime.paths.schemas.get import ListFormSchemas
from aws_api_python_runtime.paths.forms.get import ListForms
from aws_api_python_runtime.paths.sources_document.post import SubmitSourceDocument
from aws_api_python_runtime.paths.documents_document_id_forms_form_id_review.put import UpdateFormReview
from aws_api_python_runtime.paths.schemas_schema_id.put import UpdateFormSchema
from aws_api_python_runtime.paths.documents_document_id_forms_form_id_status.put import UpdateStatus


class DefaultApi(
    CreateFormReviewWorkflowTag,
    CreateFormSchema,
    DeleteFormSchema,
    GetDocument,
    GetDocumentForm,
    GetDocumentUploadUrl,
    GetFormSchema,
    GetMetrics,
    ListDocumentForms,
    ListDocuments,
    ListFormReviewWorkflowTags,
    ListFormSchemas,
    ListForms,
    SubmitSourceDocument,
    UpdateFormReview,
    UpdateFormSchema,
    UpdateStatus,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
