# coding: utf-8

"""
    AWS Docs API

    API for AWS Docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aws_api_python_runtime import schemas  # noqa: F401


class AggregateFormMetrics(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Aggregated metrics for forms
    """


    class MetaOapg:
        
        class properties:
            averageExtractionAccuracyDistance = schemas.NumberSchema
            averageExtractionAccuracyCorrectness = schemas.NumberSchema
            averageConfidence = schemas.NumberSchema
            averageExtractionTimeMilliseconds = schemas.IntSchema
            averageExtractionTimePerPageMilliseconds = schemas.IntSchema
            averageProcessingTimeMilliseconds = schemas.IntSchema
            averageProcessingTimePerPageMilliseconds = schemas.IntSchema
            averageWaitForReviewTimeMilliseconds = schemas.IntSchema
            averageWaitForReviewTimePerPageMilliseconds = schemas.IntSchema
            averageReviewTimeMilliseconds = schemas.IntSchema
            averageReviewTimePerPageMilliseconds = schemas.IntSchema
            averageEndToEndTimeMilliseconds = schemas.IntSchema
            averageEndToEndTimePerPageMilliseconds = schemas.IntSchema
            totalProcessedFormCount = schemas.IntSchema
            totalSuccessfulFormCount = schemas.IntSchema
            totalFailedFormCount = schemas.IntSchema
            __annotations__ = {
                "averageExtractionAccuracyDistance": averageExtractionAccuracyDistance,
                "averageExtractionAccuracyCorrectness": averageExtractionAccuracyCorrectness,
                "averageConfidence": averageConfidence,
                "averageExtractionTimeMilliseconds": averageExtractionTimeMilliseconds,
                "averageExtractionTimePerPageMilliseconds": averageExtractionTimePerPageMilliseconds,
                "averageProcessingTimeMilliseconds": averageProcessingTimeMilliseconds,
                "averageProcessingTimePerPageMilliseconds": averageProcessingTimePerPageMilliseconds,
                "averageWaitForReviewTimeMilliseconds": averageWaitForReviewTimeMilliseconds,
                "averageWaitForReviewTimePerPageMilliseconds": averageWaitForReviewTimePerPageMilliseconds,
                "averageReviewTimeMilliseconds": averageReviewTimeMilliseconds,
                "averageReviewTimePerPageMilliseconds": averageReviewTimePerPageMilliseconds,
                "averageEndToEndTimeMilliseconds": averageEndToEndTimeMilliseconds,
                "averageEndToEndTimePerPageMilliseconds": averageEndToEndTimePerPageMilliseconds,
                "totalProcessedFormCount": totalProcessedFormCount,
                "totalSuccessfulFormCount": totalSuccessfulFormCount,
                "totalFailedFormCount": totalFailedFormCount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageExtractionAccuracyDistance"]) -> MetaOapg.properties.averageExtractionAccuracyDistance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageExtractionAccuracyCorrectness"]) -> MetaOapg.properties.averageExtractionAccuracyCorrectness: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageConfidence"]) -> MetaOapg.properties.averageConfidence: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageExtractionTimeMilliseconds"]) -> MetaOapg.properties.averageExtractionTimeMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageExtractionTimePerPageMilliseconds"]) -> MetaOapg.properties.averageExtractionTimePerPageMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageProcessingTimeMilliseconds"]) -> MetaOapg.properties.averageProcessingTimeMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageProcessingTimePerPageMilliseconds"]) -> MetaOapg.properties.averageProcessingTimePerPageMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageWaitForReviewTimeMilliseconds"]) -> MetaOapg.properties.averageWaitForReviewTimeMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageWaitForReviewTimePerPageMilliseconds"]) -> MetaOapg.properties.averageWaitForReviewTimePerPageMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageReviewTimeMilliseconds"]) -> MetaOapg.properties.averageReviewTimeMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageReviewTimePerPageMilliseconds"]) -> MetaOapg.properties.averageReviewTimePerPageMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageEndToEndTimeMilliseconds"]) -> MetaOapg.properties.averageEndToEndTimeMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["averageEndToEndTimePerPageMilliseconds"]) -> MetaOapg.properties.averageEndToEndTimePerPageMilliseconds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalProcessedFormCount"]) -> MetaOapg.properties.totalProcessedFormCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalSuccessfulFormCount"]) -> MetaOapg.properties.totalSuccessfulFormCount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["totalFailedFormCount"]) -> MetaOapg.properties.totalFailedFormCount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["averageExtractionAccuracyDistance", "averageExtractionAccuracyCorrectness", "averageConfidence", "averageExtractionTimeMilliseconds", "averageExtractionTimePerPageMilliseconds", "averageProcessingTimeMilliseconds", "averageProcessingTimePerPageMilliseconds", "averageWaitForReviewTimeMilliseconds", "averageWaitForReviewTimePerPageMilliseconds", "averageReviewTimeMilliseconds", "averageReviewTimePerPageMilliseconds", "averageEndToEndTimeMilliseconds", "averageEndToEndTimePerPageMilliseconds", "totalProcessedFormCount", "totalSuccessfulFormCount", "totalFailedFormCount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageExtractionAccuracyDistance"]) -> typing.Union[MetaOapg.properties.averageExtractionAccuracyDistance, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageExtractionAccuracyCorrectness"]) -> typing.Union[MetaOapg.properties.averageExtractionAccuracyCorrectness, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageConfidence"]) -> typing.Union[MetaOapg.properties.averageConfidence, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageExtractionTimeMilliseconds"]) -> typing.Union[MetaOapg.properties.averageExtractionTimeMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageExtractionTimePerPageMilliseconds"]) -> typing.Union[MetaOapg.properties.averageExtractionTimePerPageMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageProcessingTimeMilliseconds"]) -> typing.Union[MetaOapg.properties.averageProcessingTimeMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageProcessingTimePerPageMilliseconds"]) -> typing.Union[MetaOapg.properties.averageProcessingTimePerPageMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageWaitForReviewTimeMilliseconds"]) -> typing.Union[MetaOapg.properties.averageWaitForReviewTimeMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageWaitForReviewTimePerPageMilliseconds"]) -> typing.Union[MetaOapg.properties.averageWaitForReviewTimePerPageMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageReviewTimeMilliseconds"]) -> typing.Union[MetaOapg.properties.averageReviewTimeMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageReviewTimePerPageMilliseconds"]) -> typing.Union[MetaOapg.properties.averageReviewTimePerPageMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageEndToEndTimeMilliseconds"]) -> typing.Union[MetaOapg.properties.averageEndToEndTimeMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["averageEndToEndTimePerPageMilliseconds"]) -> typing.Union[MetaOapg.properties.averageEndToEndTimePerPageMilliseconds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalProcessedFormCount"]) -> typing.Union[MetaOapg.properties.totalProcessedFormCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalSuccessfulFormCount"]) -> typing.Union[MetaOapg.properties.totalSuccessfulFormCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["totalFailedFormCount"]) -> typing.Union[MetaOapg.properties.totalFailedFormCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["averageExtractionAccuracyDistance", "averageExtractionAccuracyCorrectness", "averageConfidence", "averageExtractionTimeMilliseconds", "averageExtractionTimePerPageMilliseconds", "averageProcessingTimeMilliseconds", "averageProcessingTimePerPageMilliseconds", "averageWaitForReviewTimeMilliseconds", "averageWaitForReviewTimePerPageMilliseconds", "averageReviewTimeMilliseconds", "averageReviewTimePerPageMilliseconds", "averageEndToEndTimeMilliseconds", "averageEndToEndTimePerPageMilliseconds", "totalProcessedFormCount", "totalSuccessfulFormCount", "totalFailedFormCount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        averageExtractionAccuracyDistance: typing.Union[MetaOapg.properties.averageExtractionAccuracyDistance, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        averageExtractionAccuracyCorrectness: typing.Union[MetaOapg.properties.averageExtractionAccuracyCorrectness, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        averageConfidence: typing.Union[MetaOapg.properties.averageConfidence, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        averageExtractionTimeMilliseconds: typing.Union[MetaOapg.properties.averageExtractionTimeMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageExtractionTimePerPageMilliseconds: typing.Union[MetaOapg.properties.averageExtractionTimePerPageMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageProcessingTimeMilliseconds: typing.Union[MetaOapg.properties.averageProcessingTimeMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageProcessingTimePerPageMilliseconds: typing.Union[MetaOapg.properties.averageProcessingTimePerPageMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageWaitForReviewTimeMilliseconds: typing.Union[MetaOapg.properties.averageWaitForReviewTimeMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageWaitForReviewTimePerPageMilliseconds: typing.Union[MetaOapg.properties.averageWaitForReviewTimePerPageMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageReviewTimeMilliseconds: typing.Union[MetaOapg.properties.averageReviewTimeMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageReviewTimePerPageMilliseconds: typing.Union[MetaOapg.properties.averageReviewTimePerPageMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageEndToEndTimeMilliseconds: typing.Union[MetaOapg.properties.averageEndToEndTimeMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        averageEndToEndTimePerPageMilliseconds: typing.Union[MetaOapg.properties.averageEndToEndTimePerPageMilliseconds, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalProcessedFormCount: typing.Union[MetaOapg.properties.totalProcessedFormCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalSuccessfulFormCount: typing.Union[MetaOapg.properties.totalSuccessfulFormCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        totalFailedFormCount: typing.Union[MetaOapg.properties.totalFailedFormCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AggregateFormMetrics':
        return super().__new__(
            cls,
            *_args,
            averageExtractionAccuracyDistance=averageExtractionAccuracyDistance,
            averageExtractionAccuracyCorrectness=averageExtractionAccuracyCorrectness,
            averageConfidence=averageConfidence,
            averageExtractionTimeMilliseconds=averageExtractionTimeMilliseconds,
            averageExtractionTimePerPageMilliseconds=averageExtractionTimePerPageMilliseconds,
            averageProcessingTimeMilliseconds=averageProcessingTimeMilliseconds,
            averageProcessingTimePerPageMilliseconds=averageProcessingTimePerPageMilliseconds,
            averageWaitForReviewTimeMilliseconds=averageWaitForReviewTimeMilliseconds,
            averageWaitForReviewTimePerPageMilliseconds=averageWaitForReviewTimePerPageMilliseconds,
            averageReviewTimeMilliseconds=averageReviewTimeMilliseconds,
            averageReviewTimePerPageMilliseconds=averageReviewTimePerPageMilliseconds,
            averageEndToEndTimeMilliseconds=averageEndToEndTimeMilliseconds,
            averageEndToEndTimePerPageMilliseconds=averageEndToEndTimePerPageMilliseconds,
            totalProcessedFormCount=totalProcessedFormCount,
            totalSuccessfulFormCount=totalSuccessfulFormCount,
            totalFailedFormCount=totalFailedFormCount,
            _configuration=_configuration,
            **kwargs,
        )
