# coding: utf-8

# flake8: noqa

"""
    AWS Docs API

    API for AWS Docs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from aws_api_python_runtime.api_client import ApiClient

# import Configuration
from aws_api_python_runtime.configuration import Configuration

# import exceptions
from aws_api_python_runtime.exceptions import OpenApiException
from aws_api_python_runtime.exceptions import ApiAttributeError
from aws_api_python_runtime.exceptions import ApiTypeError
from aws_api_python_runtime.exceptions import ApiValueError
from aws_api_python_runtime.exceptions import ApiKeyError
from aws_api_python_runtime.exceptions import ApiException
